# Generated by Django 4.1.7 on 2023-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_delete_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ful_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
